### ISSUE TITLE
panic in madara sequencer in starknet-stack

### ISSUE THREAD

**Issue by antonio-altr** [keep-starknet-strange/madara-infra#22]
### Description
Container `starknet-stack_madara_1` exits due to panic during launch

Here's the container log:
```
$ docker logs starknet-stack_madara_1
2023-08-04 02:34:57 Substrate Node
2023-08-04 02:34:57 ✌️  version 0.1.0-alpha-9f29a203ae2
2023-08-04 02:34:57 ❤️  by Abdelhamid Bakhta <@keep-starknet-strange>:Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2023
2023-08-04 02:34:57 📋 Chain specification: Development
2023-08-04 02:34:57 🏷  Node name: fuzzy-mist-5008
2023-08-04 02:34:57 👤 Role: AUTHORITY
2023-08-04 02:34:57 💾 Database: RocksDb at /tmp/substrateolmaw4/chains/dev/db/full
2023-08-04 02:34:57 ⛓  Native runtime: madara-100 (madara-1.tx1.au1)

====================

Version: 0.1.0-alpha-9f29a203ae2

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:696:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:583:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:579:5
   5: core::panicking::panic_fmt
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panicking.rs:64:14
   6: core::result::unwrap_failed
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/result.rs:1750:5
   7: pallet_starknet::genesis_loader::read_file_to_string
   8: madara::chain_spec::testnet_genesis
   9: madara::chain_spec::development_config::{{closure}}
  10: sc_chain_spec::chain_spec::GenesisSource<G>::resolve
  11: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::assimilate_storage
  12: sp_runtime::BuildStorage::build_storage
  13: madara::genesis_block::MadaraGenesisBlockBuilder<Block,B,E>::new
  14: madara::service::new_full
  15: tokio::runtime::park::CachedParkThread::block_on
  16: tokio::runtime::context::runtime::enter_runtime
  17: tokio::runtime::runtime::Runtime::block_on
  18: sc_cli::runner::Runner<C>::run_node_until_exit
  19: madara::command::run
  20: madara::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:487:40
      std::panicking::try
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:487:40
      std::panicking::try
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/rt.rs:148:20
  24: main
  25: __libc_start_main
  26: _start


Thread 'main' panicked at 'Failed to execute cargo locate-project command: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/pallets/starknet/src/genesis_loader.rs:95

This is a bug. Please report it at:

	support.anonymous.an
```

### Steps
1. Clone repo master
2. Run `starknet-stack/run-all.sh`

**Comment by antonio-altr** [comment]
Switching to image `madara:v0.1.0-beta` solves the problem
